In [1]:
import pandas as pd
import matplotlib.pyplot as plt
import pickle
from pandas_profiling import ProfileReport
import numpy as np

In [2]:
df=pd.read_csv('Advertising.csv')  # can load the dataset using read_csv
df

Unnamed: 0     TV  Radio  Newspaper  Sales
0             1  230.1   37.8       69.2   22.1
1             2   44.5   39.3       45.1   10.4
2             3   17.2   45.9       69.3    9.3
3             4  151.5   41.3       58.5   18.5
4             5  180.8   10.8       58.4   12.9
..          ...    ...    ...        ...    ...
195         196   38.2    3.7       13.8    7.6
196         197   94.2    4.9        8.1    9.7
197         198  177.0    9.3        6.4   12.8
198         199  283.6   42.0       66.2   25.5
199         200  232.1    8.6        8.7   13.4

[200 rows x 5 columns]

In [3]:
df.head(5) # .head() returns top 5 records of dataset

Unnamed: 0     TV  Radio  Newspaper  Sales
0           1  230.1   37.8       69.2   22.1
1           2   44.5   39.3       45.1   10.4
2           3   17.2   45.9       69.3    9.3
3           4  151.5   41.3       58.5   18.5
4           5  180.8   10.8       58.4   12.9

In [4]:
df.tail()   # .tail() returns last 5 records of dataset

Unnamed: 0     TV  Radio  Newspaper  Sales
195         196   38.2    3.7       13.8    7.6
196         197   94.2    4.9        8.1    9.7
197         198  177.0    9.3        6.4   12.8
198         199  283.6   42.0       66.2   25.5
199         200  232.1    8.6        8.7   13.4

In [5]:
df.describe() # .describe() shows some imp terms related dataset like given below

Unnamed: 0          TV       Radio   Newspaper       Sales
count  200.000000  200.000000  200.000000  200.000000  200.000000
mean   100.500000  147.042500   23.264000   30.554000   14.022500
std     57.879185   85.854236   14.846809   21.778621    5.217457
min      1.000000    0.700000    0.000000    0.300000    1.600000
25%     50.750000   74.375000    9.975000   12.750000   10.375000
50%    100.500000  149.750000   22.900000   25.750000   12.900000
75%    150.250000  218.825000   36.525000   45.100000   17.400000
max    200.000000  296.400000   49.600000  114.000000   27.000000

In [6]:
df.isnull().sum()  # this command check whether any column has null valur or not

Unnamed: 0    0
TV            0
Radio         0
Newspaper     0
Sales         0
dtype: int64

In [7]:
pf = ProfileReport(df) #profilereport shows co-relation between features
pf.to_widgets()

Summarize dataset:   0%|          | 0/5 [00:00<?, ?it/s]

Generate report structure:   0%|          | 0/1 [00:00<?, ?it/s]

Render widgets:   0%|          | 0/1 [00:00<?, ?it/s]

In [8]:
df

Unnamed: 0     TV  Radio  Newspaper  Sales
0             1  230.1   37.8       69.2   22.1
1             2   44.5   39.3       45.1   10.4
2             3   17.2   45.9       69.3    9.3
3             4  151.5   41.3       58.5   18.5
4             5  180.8   10.8       58.4   12.9
..          ...    ...    ...        ...    ...
195         196   38.2    3.7       13.8    7.6
196         197   94.2    4.9        8.1    9.7
197         198  177.0    9.3        6.4   12.8
198         199  283.6   42.0       66.2   25.5
199         200  232.1    8.6        8.7   13.4

[200 rows x 5 columns]

In [9]:
pf.to_file('adervs.html')

Render HTML:   0%|          | 0/1 [00:00<?, ?it/s]

Export report to file:   0%|          | 0/1 [00:00<?, ?it/s]

In [15]:
x=df[['TV']]    # here we have taken 'TV' column as input

In [16]:
y=df['Sales']  # sales is output 

In [17]:
from sklearn.linear_model import LinearRegression
linera=LinearRegression()

In [18]:
linera.fit(x,y)

LinearRegression()

In [19]:
linera.intercept_ # this returns value of c (intercept)

7.032593549127693

In [20]:
linera.coef_      # this returns value of m (slope)

array([0.04753664])

In [21]:
file='linear_regression.sav'    # by using pickel user can save this model 
pickle.dump(linera, open('linear_regression.sav','wb'))

In [22]:
linera.predict([[45]])   # this is how user can predict the output using trained model

array([9.17174237])

In [23]:
l=[46,67,56,87,68]

In [25]:
for i in l:
    print(linera.predict([[i]]))

[9.21927901]
[10.21754846]
[9.69464541]
[11.16828127]
[10.2650851]


In [26]:
saved_model=pickle.load(open(file,'rb')) # user can load the trained model 

In [27]:
saved_model.predict([[50]])  # can also predict the value through saved model

array([9.40942557])

In [28]:
linera.score(x,y)     # this command shows accuracy of model

0.611875050850071